
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-service.mybluemix.net/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway-service.mybluemix.net
          uri: https://gateway-service.mybluemix.net
          predicates:
            - Path=/customers/**,/employees/**
        - id: payment-service
          uri: https://gateway-service.mybluemix.net
          predicates:
            - Path=/payments/**
        - id: appointment-service
          uri: https://gateway-service.mybluemix.net
          predicates:
            - Path=/appointments/**


