server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service.mybluemix.net/eureka
    registerWithEureka: false
    fetchRegistry: dalse

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: register-service
          uri: register-service.mybluemix.net
          predicates:
            - Path=/customers/**,/employees/**



