server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service.mybluemix.net/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       -  id: REGISTER-SERVICE
          uri: https://register-service.mybluemix.net
          predicates:
            - Path=/customers/**,/employees/**
       -  id: APPOINTMENT-SERVICE
          uri: https://appointment-service.mybluemix.net
          predicates:
            - Path=/appointments/**
       -  id: PAYMENT-SERVICE
          uri: https://payment-service.mybluemix.net
          predicates:
            - Path=/payments/**
       -  id: SOCIAL-NETWORK-SERVICE
          uri: https://social-network-service.mybluemix.net
          predicates:
            - Path=/comments/**,/posts/**



