server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-service.mybluemix.net/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/customers/**,/employees/**
