server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service.mybluemix.net/eureka
    register-with-eureka: false
    fetch-registry: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       -  id: REGISTER-SERVICE
          uri: lb://REGISTER-SERVICE
          predicates:
            - Path=/customers/**,/employees/**



