server:
  port: 8080

eureka:
  instance:
    hostname: eureka-service.mybluemix.net
  client:
    serviceUrl:
      defaultZone: https://eureka-service.mybluemix.net/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/customers/**,/employees/**
          filters:
            - RewritePath=/register-service/(?<segment>.*), /$\{segment}
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**


