server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: RegisterMicroservice
          uri: lb://registermicroservice
          predicates:
            - Path=/customers/**
            - Path=/employees/**
