axon:
  eventhandling:
    processors:
      customer:
        mode: subscribing
      employee:
        mode: subscribing
  axonserver:
    servers: ec2-3-145-42-138.us-east-2.compute.amazonaws.com
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://mysql8.cklvhm3suvxs.us-east-2.rds.amazonaws.com:3306/registration-inventory?verifyServerCertificate=false&useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    password: jMgsxXponHwh3pxfCUnJ
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: register-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: '8082'
