spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_REGISTER_AXON_JDBC_USER}
    url: ${MYSQL_REGISTER_AXON_JDBC_URL}
    password: ${MYSQL_REGISTER_AXON_JDBC_PASSWORD}
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081
axon:
  axonserver:
    servers: localhost
  eventhandling:
    processors[customer]:
      mode: subscribing




#Application Configuration
#server:
#  port: 8081
#  error:
#    include-message: always
#    include-binding-errors: always
#
## To See H2 Console in Browser:
## http://localhost:8081/h2-console
## Enabling H2 Console
#spring:
#  h2:
#    console:
#      enabled: true
#  # ===============================
#  # DB
#  # ===============================
#  datasource:
#    url: jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    platform: h2
#    username: sa
#    password:
#
#  # ===============================
#  # JPA / HIBERNATE
#  # ===============================
#  jpa:
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: false
#        format_sql: false
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#axon:
#  axonserver:
#    servers: localhost
#  eventhandling:
#    processors[customer]:
#      mode: subscribing